---
name: Reenable automerge
on:
  pull_request:
    branches: [main]
    types:
      - auto_merge_disabled
permissions:
  pull-requests: write
jobs:
  main:
    if: "github.event.reason == 'Base branch was modified'"
    runs-on: ubuntu-latest
    steps:
      - uses: suzuki-shunsuke/reenable-automerge-action@feat/first-pr
        with:
          github_token: ${{ github.token }}
